"""create users table

Revision ID: df0e5d8db162
Revises:
Create Date: 2026-10-03 17:23:24.056624

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df0e5d8db162"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "auth_provider",
            sa.Enum("email", "google", "apple", "guest", name="auth_provider"),
            nullable=False,
        ),
        sa.Column("provider_subject", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(auth_provider = 'email' AND email IS NOT NULL AND password_hash IS NOT NULL AND provider_subject IS NULL) OR (auth_provider IN ('google', 'apple') AND provider_subject IS NOT NULL AND provider_subject <> '' AND password_hash IS NULL) OR (auth_provider = 'guest' AND email IS NULL AND password_hash IS NULL AND provider_subject IS NULL)",
            name=op.f("ck_users_auth_provider_fields"),
        ),
        sa.CheckConstraint("position('@' in email) > 1", name=op.f("ck_users_email_format")),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("auth_provider", "provider_subject", name="uq_users_provider_subject"),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
    # Alembic does not drop PostgreSQL enum types with their table.
    sa.Enum(name="auth_provider").drop(op.get_bind(), checkfirst=True)
